eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/
server:
  port: 2006
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer
    api-b:
      path: /api-b/**
      serviceId: service-feign